In [ ]:
import matplotlib.pyplot as plt
from scipy import stats

x = [5,7,8,7,2,17,2,9,4,11,12,9,6]
y = [99,86,87,88,111,86,103,87,94,78,77,85,86]

slope, intercept, r, p, std_err = stats.linregress(x, y)

def myfunc(x):
  return slope * x + intercept
# x is input list, and output result list
mymodel = list(map(myfunc, x))

plt.scatter(x, y)
plt.plot(x, mymodel)
plt.show()

In [ ]:
#show basic tensorflow expression

import tensorflow as tf

print("TensorFlow version:", tf.__version__)

# Create a constant tensor
a = tf.constant(3.0)
# Print the constant tensor
print(a)

# Create a variable tensor
b = tf.Variable(12., name="var")
print(b)
b.assign(7)
print(b)
print(b.numpy())


a1_array = tf.constant([[10,10],[11,1.]])
print(a1_array)
a2_array = tf.constant([[1.,0.],[0.,1.]])
print(a2_array)

y = tf.matmul(a1_array, a2_array) + b

print(y)
print(y.numpy())

In [ ]:
#show basic variable result will become constant
import tensorflow as tf

# Define variables with names
var1 = tf.Variable(1.0, name="my_variable_1")
var2 = tf.Variable(2.0, name="my_variable_2")

# Use variable names in the computation graph
result = var1 + var2

# Print the variable names
print("Variable 1 name:", var1.name)
print("Variable 2 name:", var2.name)

print(var1)
print(var2)
print(result)



In [ ]:
#basic multiple in tensorflow

x1 = tf.constant([[10,10,10]])
print("x1:")
print(x1)
x2 = tf.reshape(x1,[3,1])
print("x2:")
print(x2)
# 1~4
y = tf.range(1, 5)
print("y:")
print(y)

#tensor multiply
print("tf.multiply(x2, y)=")
print(tf.multiply(x2, y))
print("tf.multiply(x1, x2)=")
print(tf.multiply(x1, x2))
#matrix multiply
print("tf.matmul(x1, x2)=")
print(tf.matmul(x1, x2))

In [1]:
import numpy as np
from tensorflow.keras.utils import to_categorical

# Example class labels
class_labels = np.array([0, 1, 2, 1])

# Convert to one-hot encoding
one_hot_labels = to_categorical(class_labels)

print(one_hot_labels)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
